name: Auto Train DevOps Model

on:
  push:
    paths:
      - 'data/raw/devops_qa.json'   
jobs:
  train:
    runs-on: self-hosted

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Preprocess Data
      run: |
        python training/preprocess.py

    - name: Train Model
      run: |
        python training/train.py

    - name: Save Model Artifact
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: models/lora_adapter/